version: '3'
services:
  web:
    build: .
    image: raan_web
    environment:
      - RAILS_ENV=production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/raan
    container_name: raan_web
    ports:
      - "3000:3000"